/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace AndrewKalotayAssociates {

using System;
using System.Runtime.InteropServices;

public class Duration : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Duration(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Duration obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Duration() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AkaApiPINVOKE.delete_Duration(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public Duration(double d, double c) : this(AkaApiPINVOKE.new_Duration(d, c), true) {
  }

  public double duration {
    set {
      AkaApiPINVOKE.Duration_duration_set(swigCPtr, value);
    } 
    get {
      double ret = AkaApiPINVOKE.Duration_duration_get(swigCPtr);
      return ret;
    } 
  }

  public double convexity {
    set {
      AkaApiPINVOKE.Duration_convexity_set(swigCPtr, value);
    } 
    get {
      double ret = AkaApiPINVOKE.Duration_convexity_get(swigCPtr);
      return ret;
    } 
  }

}

}
