/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace AndrewKalotayAssociates {

using System;
using System.Runtime.InteropServices;

public class Initialization : Status {
  private HandleRef swigCPtr;

  internal Initialization(IntPtr cPtr, bool cMemoryOwn) : base(AkaApiPINVOKE.Initialization_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Initialization obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Initialization() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AkaApiPINVOKE.delete_Initialization(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public Initialization() : this(AkaApiPINVOKE.new_Initialization__SWIG_0(), true) {
  }

  public Initialization(int key, string uname) : this(AkaApiPINVOKE.new_Initialization__SWIG_1(key, uname), true) {
  }

  public Initialization(string keyfilename) : this(AkaApiPINVOKE.new_Initialization__SWIG_2(keyfilename), true) {
  }

  public void ShutdownAutomatically(bool arg0) {
    AkaApiPINVOKE.Initialization_ShutdownAutomatically(swigCPtr, arg0);
  }

  public static void Shutdown() {
    AkaApiPINVOKE.Initialization_Shutdown();
  }

  public int Authorize(int key, string uname) {
    int ret = AkaApiPINVOKE.Initialization_Authorize__SWIG_0(swigCPtr, key, uname);
    return ret;
  }

  public int Authorize(string keyfilename) {
    int ret = AkaApiPINVOKE.Initialization_Authorize__SWIG_1(swigCPtr, keyfilename);
    return ret;
  }

  public int Authorize() {
    int ret = AkaApiPINVOKE.Initialization_Authorize__SWIG_2(swigCPtr);
    return ret;
  }

  public Date Expiration() {
    Date ret = new Date(AkaApiPINVOKE.Initialization_Expiration(swigCPtr), true);
    return ret;
  }

  public static double Version() {
    double ret = AkaApiPINVOKE.Initialization_Version();
    return ret;
  }

  public static string VersionString() {
    string ret = AkaApiPINVOKE.Initialization_VersionString();
    return ret;
  }

}

}
