/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace AndrewKalotayAssociates {

using System;
using System.Runtime.InteropServices;

public class SinkingFundStatus : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SinkingFundStatus(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(SinkingFundStatus obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~SinkingFundStatus() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AkaApiPINVOKE.delete_SinkingFundStatus(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public double outstanding {
    set {
      AkaApiPINVOKE.SinkingFundStatus_outstanding_set(swigCPtr, value);
    } 
    get {
      double ret = AkaApiPINVOKE.SinkingFundStatus_outstanding_get(swigCPtr);
      return ret;
    } 
  }

  public double accumulation {
    set {
      AkaApiPINVOKE.SinkingFundStatus_accumulation_set(swigCPtr, value);
    } 
    get {
      double ret = AkaApiPINVOKE.SinkingFundStatus_accumulation_get(swigCPtr);
      return ret;
    } 
  }

  public SinkingFundStatus(uint os, uint ac) : this(AkaApiPINVOKE.new_SinkingFundStatus__SWIG_0(os, ac), true) {
  }

  public SinkingFundStatus(double os, double ac) : this(AkaApiPINVOKE.new_SinkingFundStatus__SWIG_1(os, ac), true) {
  }

  public SinkingFundStatus() : this(AkaApiPINVOKE.new_SinkingFundStatus__SWIG_2(), true) {
  }

}

}
