/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace AndrewKalotayAssociates {

using System;
using System.Runtime.InteropServices;

public class Status : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Status(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Status obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Status() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AkaApiPINVOKE.delete_Status(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public Status() : this(AkaApiPINVOKE.new_Status(), true) {
  }

  public int Error() {
    int ret = AkaApiPINVOKE.Status_Error(swigCPtr);
    return ret;
  }

  public int WarningCount() {
    int ret = AkaApiPINVOKE.Status_WarningCount(swigCPtr);
    return ret;
  }

  public int Warning(int idx) {
    int ret = AkaApiPINVOKE.Status_Warning(swigCPtr, idx);
    return ret;
  }

  public static string ErrorString(int arg0) {
    string ret = AkaApiPINVOKE.Status_ErrorString__SWIG_0(arg0);
    return ret;
  }

  public string ErrorString() {
    string ret = AkaApiPINVOKE.Status_ErrorString__SWIG_1(swigCPtr);
    return ret;
  }

  public string WarningString(int idx) {
    string ret = AkaApiPINVOKE.Status_WarningString(swigCPtr, idx);
    return ret;
  }

  public void Clear() {
    AkaApiPINVOKE.Status_Clear(swigCPtr);
  }

}

}
