/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kalotay.akalib;

public class Initialization extends Status {
  private long swigCPtr;

  protected Initialization(long cPtr, boolean cMemoryOwn) {
    super(AkaApiJNI.Initialization_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Initialization obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AkaApiJNI.delete_Initialization(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Initialization() {
    this(AkaApiJNI.new_Initialization__SWIG_0(), true);
  }

  public Initialization(int key, String uname) {
    this(AkaApiJNI.new_Initialization__SWIG_1(key, uname), true);
  }

  public Initialization(String keyfilename) {
    this(AkaApiJNI.new_Initialization__SWIG_2(keyfilename), true);
  }

  public void ShutdownAutomatically(boolean arg0) {
    AkaApiJNI.Initialization_ShutdownAutomatically(swigCPtr, this, arg0);
  }

  public static void Shutdown() {
    AkaApiJNI.Initialization_Shutdown();
  }

  public int Authorize(int key, String uname) {
    return AkaApiJNI.Initialization_Authorize__SWIG_0(swigCPtr, this, key, uname);
  }

  public int Authorize(String keyfilename) {
    return AkaApiJNI.Initialization_Authorize__SWIG_1(swigCPtr, this, keyfilename);
  }

  public int Authorize() {
    return AkaApiJNI.Initialization_Authorize__SWIG_2(swigCPtr, this);
  }

  public Date Expiration() {
    return new Date(AkaApiJNI.Initialization_Expiration(swigCPtr, this), true);
  }

  public static double Version() {
    return AkaApiJNI.Initialization_Version();
  }

  public static String VersionString() {
    return AkaApiJNI.Initialization_VersionString();
  }

}
