/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kalotay.akalib;

public class ScenarioAnalysis {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ScenarioAnalysis(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ScenarioAnalysis obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AkaApiJNI.delete_ScenarioAnalysis(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRedeemed(ScenarioAnalysis.REDEEMED value) {
    AkaApiJNI.ScenarioAnalysis_redeemed_set(swigCPtr, this, value.swigValue());
  }

  public ScenarioAnalysis.REDEEMED getRedeemed() {
    return ScenarioAnalysis.REDEEMED.swigToEnum(AkaApiJNI.ScenarioAnalysis_redeemed_get(swigCPtr, this));
  }

  public void setFlowwhen(int value) {
    AkaApiJNI.ScenarioAnalysis_flowwhen_set(swigCPtr, this, value);
  }

  public int getFlowwhen() {
    return AkaApiJNI.ScenarioAnalysis_flowwhen_get(swigCPtr, this);
  }

  public void setEfficiency(double value) {
    AkaApiJNI.ScenarioAnalysis_efficiency_set(swigCPtr, this, value);
  }

  public double getEfficiency() {
    return AkaApiJNI.ScenarioAnalysis_efficiency_get(swigCPtr, this);
  }

  public void setReinvestment(double value) {
    AkaApiJNI.ScenarioAnalysis_reinvestment_set(swigCPtr, this, value);
  }

  public double getReinvestment() {
    return AkaApiJNI.ScenarioAnalysis_reinvestment_get(swigCPtr, this);
  }

  public static String redeemstring(ScenarioAnalysis.REDEEMED arg0) {
    return AkaApiJNI.ScenarioAnalysis_redeemstring__SWIG_0(arg0.swigValue());
  }

  public String redeemstring() {
    return AkaApiJNI.ScenarioAnalysis_redeemstring__SWIG_1(swigCPtr, this);
  }

  public ScenarioAnalysis() {
    this(AkaApiJNI.new_ScenarioAnalysis(), true);
  }

  public final static class REDEEMED {
    public final static ScenarioAnalysis.REDEEMED NOTREDEEMED = new ScenarioAnalysis.REDEEMED("NOTREDEEMED");
    public final static ScenarioAnalysis.REDEEMED CALL = new ScenarioAnalysis.REDEEMED("CALL");
    public final static ScenarioAnalysis.REDEEMED PUT = new ScenarioAnalysis.REDEEMED("PUT");
    public final static ScenarioAnalysis.REDEEMED SINK = new ScenarioAnalysis.REDEEMED("SINK");
    public final static ScenarioAnalysis.REDEEMED MATURITY = new ScenarioAnalysis.REDEEMED("MATURITY");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static REDEEMED swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + REDEEMED.class + " with value " + swigValue);
    }

    private REDEEMED(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private REDEEMED(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private REDEEMED(String swigName, REDEEMED swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static REDEEMED[] swigValues = { NOTREDEEMED, CALL, PUT, SINK, MATURITY };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
