/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kalotay.akalib;

public class Status {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Status(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Status obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AkaApiJNI.delete_Status(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Status() {
    this(AkaApiJNI.new_Status(), true);
  }

  public int Error() {
    return AkaApiJNI.Status_Error(swigCPtr, this);
  }

  public int WarningCount() {
    return AkaApiJNI.Status_WarningCount(swigCPtr, this);
  }

  public int Warning(int idx) {
    return AkaApiJNI.Status_Warning(swigCPtr, this, idx);
  }

  public static String ErrorString(int arg0) {
    return AkaApiJNI.Status_ErrorString__SWIG_0(arg0);
  }

  public String ErrorString() {
    return AkaApiJNI.Status_ErrorString__SWIG_1(swigCPtr, this);
  }

  public String WarningString(int idx) {
    return AkaApiJNI.Status_WarningString(swigCPtr, this, idx);
  }

  public void Clear() {
    AkaApiJNI.Status_Clear(swigCPtr, this);
  }

}
