/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kalotay.akalib;

public class Value extends Status {
  private long swigCPtr;

  protected Value(long cPtr, boolean cMemoryOwn) {
    super(AkaApiJNI.Value_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Value obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AkaApiJNI.delete_Value(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Value(Bond arg0, Date pvdate) {
    this(AkaApiJNI.new_Value__SWIG_1(Bond.getCPtr(arg0), arg0, Date.getCPtr(pvdate), pvdate), true);
  }

  public Value(Bond arg0, Date pvdate, Date tradedate) {
    this(AkaApiJNI.new_Value__SWIG_2(Bond.getCPtr(arg0), arg0, Date.getCPtr(pvdate), pvdate, Date.getCPtr(tradedate), tradedate), true);
  }

  public Value(Bond arg0, InterestRateModel arg1, Date pvdate) {
    this(AkaApiJNI.new_Value__SWIG_3(Bond.getCPtr(arg0), arg0, InterestRateModel.getCPtr(arg1), arg1, Date.getCPtr(pvdate), pvdate), true);
  }

  public Value(Bond arg0, InterestRateModel arg1, Date pvdate, Date tradedate) {
    this(AkaApiJNI.new_Value__SWIG_4(Bond.getCPtr(arg0), arg0, InterestRateModel.getCPtr(arg1), arg1, Date.getCPtr(pvdate), pvdate, Date.getCPtr(tradedate), tradedate), true);
  }

  public Value(Bond arg0, InterestRateModel arg1, SinkingFundStatus arg2, Date pvdate) {
    this(AkaApiJNI.new_Value__SWIG_5(Bond.getCPtr(arg0), arg0, InterestRateModel.getCPtr(arg1), arg1, SinkingFundStatus.getCPtr(arg2), arg2, Date.getCPtr(pvdate), pvdate), true);
  }

  public Value(Bond arg0, InterestRateModel arg1, SinkingFundStatus arg2, Date pvdate, Date tradedate) {
    this(AkaApiJNI.new_Value__SWIG_6(Bond.getCPtr(arg0), arg0, InterestRateModel.getCPtr(arg1), arg1, SinkingFundStatus.getCPtr(arg2), arg2, Date.getCPtr(pvdate), pvdate, Date.getCPtr(tradedate), tradedate), true);
  }

  public int Reset(Bond arg0, Date pvdate) {
    return AkaApiJNI.Value_Reset__SWIG_0(swigCPtr, this, Bond.getCPtr(arg0), arg0, Date.getCPtr(pvdate), pvdate);
  }

  public int Reset(Bond arg0, Date pvdate, Date tradedate) {
    return AkaApiJNI.Value_Reset__SWIG_1(swigCPtr, this, Bond.getCPtr(arg0), arg0, Date.getCPtr(pvdate), pvdate, Date.getCPtr(tradedate), tradedate);
  }

  public int Reset(Bond arg0, InterestRateModel arg1, Date pvdate) {
    return AkaApiJNI.Value_Reset__SWIG_2(swigCPtr, this, Bond.getCPtr(arg0), arg0, InterestRateModel.getCPtr(arg1), arg1, Date.getCPtr(pvdate), pvdate);
  }

  public int Reset(Bond arg0, InterestRateModel arg1, Date pvdate, Date tradedate) {
    return AkaApiJNI.Value_Reset__SWIG_3(swigCPtr, this, Bond.getCPtr(arg0), arg0, InterestRateModel.getCPtr(arg1), arg1, Date.getCPtr(pvdate), pvdate, Date.getCPtr(tradedate), tradedate);
  }

  public int Reset(Bond arg0, InterestRateModel arg1, SinkingFundStatus arg2, Date pvdate) {
    return AkaApiJNI.Value_Reset__SWIG_4(swigCPtr, this, Bond.getCPtr(arg0), arg0, InterestRateModel.getCPtr(arg1), arg1, SinkingFundStatus.getCPtr(arg2), arg2, Date.getCPtr(pvdate), pvdate);
  }

  public int Reset(Bond arg0, InterestRateModel arg1, SinkingFundStatus arg2, Date pvdate, Date tradedate) {
    return AkaApiJNI.Value_Reset__SWIG_5(swigCPtr, this, Bond.getCPtr(arg0), arg0, InterestRateModel.getCPtr(arg1), arg1, SinkingFundStatus.getCPtr(arg2), arg2, Date.getCPtr(pvdate), pvdate, Date.getCPtr(tradedate), tradedate);
  }

  public static double getBadValue() {
    return AkaApiJNI.Value_BadValue_get();
  }

  public int FlowCount() {
    return AkaApiJNI.Value_FlowCount(swigCPtr, this);
  }

  public int FlowType(int arg0) {
    return AkaApiJNI.Value_FlowType__SWIG_0(swigCPtr, this, arg0);
  }

  public boolean FlowType(int idx, Value.FLOWTYPE t) {
    return AkaApiJNI.Value_FlowType__SWIG_1(swigCPtr, this, idx, t.swigValue());
  }

  public int FirstFlow() {
    return AkaApiJNI.Value_FirstFlow(swigCPtr, this);
  }

  public Date FlowDate(int arg0) {
    return new Date(AkaApiJNI.Value_FlowDate(swigCPtr, this, arg0), true);
  }

  public double YearsTo(int arg0) {
    return AkaApiJNI.Value_YearsTo(swigCPtr, this, arg0);
  }

  public double Interest(int arg0) {
    return AkaApiJNI.Value_Interest(swigCPtr, this, arg0);
  }

  public double Principal(int arg0) {
    return AkaApiJNI.Value_Principal(swigCPtr, this, arg0);
  }

  public double PrincipalPrice(int arg0) {
    return AkaApiJNI.Value_PrincipalPrice(swigCPtr, this, arg0);
  }

  public double Accrued(int arg0) {
    return AkaApiJNI.Value_Accrued__SWIG_0(swigCPtr, this, arg0);
  }

  public double CallPrice(int arg0) {
    return AkaApiJNI.Value_CallPrice(swigCPtr, this, arg0);
  }

  public double PutPrice(int arg0) {
    return AkaApiJNI.Value_PutPrice(swigCPtr, this, arg0);
  }

  public String BondName() {
    return AkaApiJNI.Value_BondName(swigCPtr, this);
  }

  public double Accrued() {
    return AkaApiJNI.Value_Accrued__SWIG_1(swigCPtr, this);
  }

  public int AccruedDays() {
    return AkaApiJNI.Value_AccruedDays(swigCPtr, this);
  }

  public double AccruedOn(Date arg0) {
    return AkaApiJNI.Value_AccruedOn(swigCPtr, this, Date.getCPtr(arg0), arg0);
  }

  public boolean SetYieldMethod(Bond.YIELD_METHOD arg0) {
    return AkaApiJNI.Value_SetYieldMethod(swigCPtr, this, arg0.swigValue());
  }

  public Bond.YIELD_METHOD GetYieldMethod() {
    return Bond.YIELD_METHOD.swigToEnum(AkaApiJNI.Value_GetYieldMethod(swigCPtr, this));
  }

  public double YieldToCall(double price) {
    return AkaApiJNI.Value_YieldToCall(swigCPtr, this, price);
  }

  public double YieldToPut(double price) {
    return AkaApiJNI.Value_YieldToPut(swigCPtr, this, price);
  }

  public double YieldToMaturity(double price) {
    return AkaApiJNI.Value_YieldToMaturity(swigCPtr, this, price);
  }

  public double YieldToWorst(double price, boolean also_to_sink) {
    return AkaApiJNI.Value_YieldToWorst__SWIG_0(swigCPtr, this, price, also_to_sink);
  }

  public double YieldToWorst(double price) {
    return AkaApiJNI.Value_YieldToWorst__SWIG_1(swigCPtr, this, price);
  }

  public double YieldToWorst(double price, SWIGTYPE_p_int flowindex, boolean also_to_sink) {
    return AkaApiJNI.Value_YieldToWorst__SWIG_2(swigCPtr, this, price, SWIGTYPE_p_int.getCPtr(flowindex), also_to_sink);
  }

  public double YieldToWorst(double price, SWIGTYPE_p_int flowindex) {
    return AkaApiJNI.Value_YieldToWorst__SWIG_3(swigCPtr, this, price, SWIGTYPE_p_int.getCPtr(flowindex));
  }

  public double WeightedAverageMaturity(double price) {
    return AkaApiJNI.Value_WeightedAverageMaturity(swigCPtr, this, price);
  }

  public Duration ModifiedDuration(double px) {
    return new Duration(AkaApiJNI.Value_ModifiedDuration(swigCPtr, this, px), true);
  }

  public double YieldToFlow(int arg0, double price, boolean as_cashflow_yield) {
    return AkaApiJNI.Value_YieldToFlow__SWIG_0(swigCPtr, this, arg0, price, as_cashflow_yield);
  }

  public double YieldToFlow(int arg0, double price) {
    return AkaApiJNI.Value_YieldToFlow__SWIG_1(swigCPtr, this, arg0, price);
  }

  public Duration ModifiedDurationToFlow(int arg0, double price, double yield) {
    return new Duration(AkaApiJNI.Value_ModifiedDurationToFlow(swigCPtr, this, arg0, price, yield), true);
  }

  public double ytm2price(double arg0) {
    return AkaApiJNI.Value_ytm2price(swigCPtr, this, arg0);
  }

  public double ytc2price(double arg0) {
    return AkaApiJNI.Value_ytc2price(swigCPtr, this, arg0);
  }

  public double ytp2price(double arg0) {
    return AkaApiJNI.Value_ytp2price(swigCPtr, this, arg0);
  }

  public double Price(double oas) {
    return AkaApiJNI.Value_Price__SWIG_0(swigCPtr, this, oas);
  }

  public double Price(Quote arg0) {
    return AkaApiJNI.Value_Price__SWIG_1(swigCPtr, this, Quote.getCPtr(arg0), arg0);
  }

  public double OAS(double price) {
    return AkaApiJNI.Value_OAS__SWIG_0(swigCPtr, this, price);
  }

  public double OAS(Quote arg0) {
    return AkaApiJNI.Value_OAS__SWIG_1(swigCPtr, this, Quote.getCPtr(arg0), arg0);
  }

  public double OptionValue(double oas) {
    return AkaApiJNI.Value_OptionValue__SWIG_0(swigCPtr, this, oas);
  }

  public double OptionValue(Quote arg0) {
    return AkaApiJNI.Value_OptionValue__SWIG_1(swigCPtr, this, Quote.getCPtr(arg0), arg0);
  }

  public double PriceToFlow(int arg0, double yield, boolean as_cashflow_yield) {
    return AkaApiJNI.Value_PriceToFlow__SWIG_0(swigCPtr, this, arg0, yield, as_cashflow_yield);
  }

  public double PriceToFlow(int arg0, double yield) {
    return AkaApiJNI.Value_PriceToFlow__SWIG_1(swigCPtr, this, arg0, yield);
  }

  public double PriceToWorst(double yield, boolean also_to_sinks) {
    return AkaApiJNI.Value_PriceToWorst__SWIG_0(swigCPtr, this, yield, also_to_sinks);
  }

  public double PriceToWorst(double yield) {
    return AkaApiJNI.Value_PriceToWorst__SWIG_1(swigCPtr, this, yield);
  }

  public double PriceToWorst(double yield, SWIGTYPE_p_int flowindex, boolean also_to_sinks) {
    return AkaApiJNI.Value_PriceToWorst__SWIG_2(swigCPtr, this, yield, SWIGTYPE_p_int.getCPtr(flowindex), also_to_sinks);
  }

  public double PriceToWorst(double yield, SWIGTYPE_p_int flowindex) {
    return AkaApiJNI.Value_PriceToWorst__SWIG_3(swigCPtr, this, yield, SWIGTYPE_p_int.getCPtr(flowindex));
  }

  public Duration EffectiveDuration(double oas, double durationbp) {
    return new Duration(AkaApiJNI.Value_EffectiveDuration__SWIG_0(swigCPtr, this, oas, durationbp), true);
  }

  public Duration EffectiveDuration(double oas) {
    return new Duration(AkaApiJNI.Value_EffectiveDuration__SWIG_1(swigCPtr, this, oas), true);
  }

  public Duration EffectiveDuration(Quote arg0, double durationbp) {
    return new Duration(AkaApiJNI.Value_EffectiveDuration__SWIG_2(swigCPtr, this, Quote.getCPtr(arg0), arg0, durationbp), true);
  }

  public Duration EffectiveDuration(Quote arg0) {
    return new Duration(AkaApiJNI.Value_EffectiveDuration__SWIG_3(swigCPtr, this, Quote.getCPtr(arg0), arg0), true);
  }

  public double UpDuration(double oas, double durationbp) {
    return AkaApiJNI.Value_UpDuration__SWIG_0(swigCPtr, this, oas, durationbp);
  }

  public double UpDuration(double oas) {
    return AkaApiJNI.Value_UpDuration__SWIG_1(swigCPtr, this, oas);
  }

  public double DownDuration(double oas, double durationbp) {
    return AkaApiJNI.Value_DownDuration__SWIG_0(swigCPtr, this, oas, durationbp);
  }

  public double DownDuration(double oas) {
    return AkaApiJNI.Value_DownDuration__SWIG_1(swigCPtr, this, oas);
  }

  public double UpDuration(Quote arg0, double durationbp) {
    return AkaApiJNI.Value_UpDuration__SWIG_2(swigCPtr, this, Quote.getCPtr(arg0), arg0, durationbp);
  }

  public double UpDuration(Quote arg0) {
    return AkaApiJNI.Value_UpDuration__SWIG_3(swigCPtr, this, Quote.getCPtr(arg0), arg0);
  }

  public double DownDuration(Quote arg0, double durationbp) {
    return AkaApiJNI.Value_DownDuration__SWIG_2(swigCPtr, this, Quote.getCPtr(arg0), arg0, durationbp);
  }

  public double DownDuration(Quote arg0) {
    return AkaApiJNI.Value_DownDuration__SWIG_3(swigCPtr, this, Quote.getCPtr(arg0), arg0);
  }

  public Duration KeyRateDuration(double oas, double durationbp, double year) {
    return new Duration(AkaApiJNI.Value_KeyRateDuration__SWIG_0(swigCPtr, this, oas, durationbp, year), true);
  }

  public Duration KeyRateDuration(Quote arg0, double durationbp, double year) {
    return new Duration(AkaApiJNI.Value_KeyRateDuration__SWIG_1(swigCPtr, this, Quote.getCPtr(arg0), arg0, durationbp, year), true);
  }

  public Duration KeyRateDuration(double oas, double durationbp, double year, double width) {
    return new Duration(AkaApiJNI.Value_KeyRateDuration__SWIG_2(swigCPtr, this, oas, durationbp, year, width), true);
  }

  public Duration KeyRateDuration(Quote arg0, double durationbp, double year, double width) {
    return new Duration(AkaApiJNI.Value_KeyRateDuration__SWIG_3(swigCPtr, this, Quote.getCPtr(arg0), arg0, durationbp, year, width), true);
  }

  public Duration KeyRateDuration(double oas, double durationbp, double year, double leftanchoryear, double rightanchoryear) {
    return new Duration(AkaApiJNI.Value_KeyRateDuration__SWIG_4(swigCPtr, this, oas, durationbp, year, leftanchoryear, rightanchoryear), true);
  }

  public Duration KeyRateDuration(Quote arg0, double durationbp, double year, double leftanchoryear, double rightanchoryear) {
    return new Duration(AkaApiJNI.Value_KeyRateDuration__SWIG_5(swigCPtr, this, Quote.getCPtr(arg0), arg0, durationbp, year, leftanchoryear, rightanchoryear), true);
  }

  public double Discount(double value, double fromtime, double oas) {
    return AkaApiJNI.Value_Discount__SWIG_0(swigCPtr, this, value, fromtime, oas);
  }

  public double Discount(double value, double fromtime) {
    return AkaApiJNI.Value_Discount__SWIG_1(swigCPtr, this, value, fromtime);
  }

  public double GetRate(double year) {
    return AkaApiJNI.Value_GetRate(swigCPtr, this, year);
  }

  public double GetFactor(double year) {
    return AkaApiJNI.Value_GetFactor(swigCPtr, this, year);
  }

  public boolean AnalyzeScenario(InterestRateScenario arg0, double oas, ScenarioAnalysis arg2) {
    return AkaApiJNI.Value_AnalyzeScenario__SWIG_0(swigCPtr, this, InterestRateScenario.getCPtr(arg0), arg0, oas, ScenarioAnalysis.getCPtr(arg2), arg2);
  }

  public boolean AnalyzeScenario(InterestRateScenario arg0, Quote arg1, ScenarioAnalysis arg2) {
    return AkaApiJNI.Value_AnalyzeScenario__SWIG_1(swigCPtr, this, InterestRateScenario.getCPtr(arg0), arg0, Quote.getCPtr(arg1), arg1, ScenarioAnalysis.getCPtr(arg2), arg2);
  }

  public double AssetSwapSpread(double price) {
    return AkaApiJNI.Value_AssetSwapSpread(swigCPtr, this, price);
  }

  public double ISpread(double price) {
    return AkaApiJNI.Value_ISpread(swigCPtr, this, price);
  }

  public final static class FLOWTYPE {
    public final static Value.FLOWTYPE INTEREST = new Value.FLOWTYPE("INTEREST", AkaApiJNI.Value_INTEREST_get());
    public final static Value.FLOWTYPE PRINCIPAL = new Value.FLOWTYPE("PRINCIPAL", AkaApiJNI.Value_PRINCIPAL_get());
    public final static Value.FLOWTYPE CALLOPTION = new Value.FLOWTYPE("CALLOPTION", AkaApiJNI.Value_CALLOPTION_get());
    public final static Value.FLOWTYPE PUTOPTION = new Value.FLOWTYPE("PUTOPTION", AkaApiJNI.Value_PUTOPTION_get());
    public final static Value.FLOWTYPE PSEUDO_REGULAR = new Value.FLOWTYPE("PSEUDO_REGULAR", AkaApiJNI.Value_PSEUDO_REGULAR_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static FLOWTYPE swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + FLOWTYPE.class + " with value " + swigValue);
    }

    private FLOWTYPE(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private FLOWTYPE(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private FLOWTYPE(String swigName, FLOWTYPE swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static FLOWTYPE[] swigValues = { INTEREST, PRINCIPAL, CALLOPTION, PUTOPTION, PSEUDO_REGULAR };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
